package main

var dataMappings = map[string]string{
	" ":                  " ",
	"Change Up":          "CH",
	"Fastball":           "FB",
	"Curveball":          "CB",
	"Slider":             "SL",
	"Hard Hit":           "H",
	"Routine Hit":        "R",
	"Weak Hit":           "W",
	"Standing Strikeout": "uK",
	"Strikeout":          "K",
	"Walk":               "BB",
	"Hit By Pitch":       "HBP",
	"Grounder":           "G",
	"Line-Drive":         "L",
	"Fly":                "F",
	"Pitcher":            "1",
	"Catcher":            "2",
	"First Base":         "3",
	"Second Base":        "4",
	"Shortstop":          "6",
	"Third Base":         "5",
	"Right Field":        "9",
	"Center Field":       "8",
	"Left Field":         "7",
	"Left Handed":        "LHP",
	"Right Handed":       "RHP"}
